version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: taskmanager_user
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: taskmanager_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U taskmanager_user -d taskmanager_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py create_roles && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://taskmanager_user:secretpassword@db:5432/taskmanager_db

  redis:
    image: redis:7
    ports:
      - "6379:6379"    

volumes:
  pgdata: